### ISSUE TITLE
tick upgrade rats don't work on any block anymore

### ISSUE THREAD

**Issue by domenicop-1991** [AllTheMods/ATM-6#1000]
**pack version:** ATM-6 1.5.0

**Problem:** tick upgrade rats don't work on any block anymore

**Steps to reproduce the behavior:**
place any block to speed up (es: lilypad of fertility)
place one or more rats with _Tick Accele-Rat-Or_ on them
nothing changes, ticks do not increase and speed remains unchanged

**Comment by whatthedrunk** [comment]
I believe this was fixed in a Rats update that came out after we updated. Try manually updating for now but we will add the update in next week's build.

**Comment by Popomain** [comment]
Is this fixed in 1.5.1?

**Comment by domenicop-1991** [comment]
we have updated the server to 1.5.1 but the problem remained, the rats no longer increase the ticks of anything
