### ISSUE TITLE
ATM6 1.6.3 Tree Growth Bug

### ISSUE THREAD

**Issue by ixItZxPiExi** [AllTheMods/ATM-6#1602]
Upon logging into my world the oak trees in my farm that are 6 blocks above an open area grow through the dirt blocks they are placed on, and approximately 4 blocks into the stone beneath. This is a tree farm using Industrial Foregoing

**To Reproduce**
1. Stop World
2. Restart Instance of ATM6
3. Join back into the world
4. Upon loading in the trees are grown through the block they were planted on. 

**Screenshots**
![2021-05-12_05 04 55](https://user-images.githubusercontent.com/35822510/117961307-9611c780-b2e3-11eb-8ab5-4c9be99d589d.png)
![2021-05-12_05 12 27](https://user-images.githubusercontent.com/35822510/117961311-9742f480-b2e3-11eb-9fab-d906e68dbc40.png)

**Additional Context**
The tree farm is using industrial foregoing for automation reguarding the planting and collection of said trees. They are oak trees. Have not tested other types.

**Log**
[2021-05-12-1.log](https://github.com/AllTheMods/ATM-6/files/6465554/2021-05-12-1.log)

**Comment by ronaldjan17** [comment]
I've been experiencing it as well. It is not specific to the type of tree. Even trees where it would normally be pretty tame, like birch, even trees from other mods.

High likelyhood that its related to the biome. (I have another tree farm in a different biome and not experiencing that there)

**Comment by lazystudent3** [comment]
I am experiencing the same kind of bug(?) but in my case its Create Mod farm. I am using vanilla and modded saplings. In my case, it also leave huge holes.
(First time posting something on github so I apologize for any mistake :) )
![bug](https://user-images.githubusercontent.com/74244333/118266242-9912e080-b4ba-11eb-8997-3118c46b3c8f.png)
![bug2](https://user-images.githubusercontent.com/74244333/118266252-9a440d80-b4ba-11eb-822e-e114f509424d.png)

**Comment by nods0123** [comment]
Yeah, still an issue and it prevents my automatic tree farm from working. Anyone got a fix yet? Also, doesn't seem to be biome specific, I made a new world and tried planting Spruce trees in places such as rivers, oceans, etc and it had the same issue. It's not 100% of the time but it is enough of the time. Also, I noticed Ebony trees do it if they have anything surrounding them.

**Comment by lazystudent3** [comment]
@nods0123  I still didnt find solution for that, unfortunately. Like u said it stops tree farm from working. I noticed that when I afk'ed right next to my farm it was doing ok but when i leave for a short moment it happens. I can also add that I plant oak, spruce, 2 diffrent cherry saplings in my farm and this happens to all of them.

**Comment by MysteryMerijn** [comment]
1.6.4 solved it for me.

Looks like it was an issue with BYG.
https://github.com/CorgiTaco/BYG/issues/468

**Comment by nods0123** [comment]
I'll try updating to 1.6.4 and see if that works.
It's a shame really, because I was using therecently added quests as a guide for the mods, but 1.6.4 says it removed them. I'll post an update on how it goes.

**Comment by nods0123** [comment]
After a little bit of testing, my results, so far:
Setup: Spruce Planks border then a Dirt border, both w/ hole underneath (long enough that, should logs dig underground, it won't destroy any further block.
> Setup w/ Spruce Planks border had an Ebony tree grow next to/on it. The Ebony tree broke through the planks, but not through the dirt.
> Setup w/ Dirt border had an Ebony tree grow on it. The Ebony tree didn't grow underground whatsoever.
> Setup w/ Dirt border had a 3x3 Spruce tree grow, to which some of the tree spilled underground, but did not destroy the grass block it was on.

So, so far, it seems to be somewhat fixed, but will still destroy certain blocks, should they be "in the way." Also, given there is at least an empty space underneath (haven't tested w/ solid underground yet), the tree will still grow underneath, but will no longer destroy the grass block (or, at least, 3x3 Spruce trees are). I will let everyone know if I find out any more.

**Comment by whatthedrunk** [comment]
Fixed in latest.

**Comment by deathbutton1** [comment]
This was only partially fixed. It doesn't destroy the dirt directly below the sapling anymore, but it will still destroy machines under it.  It looks like this was fixed in BYG 1.2.9 but ATM is on 1.2.8. CorgiTaco/BYG#505
