### ISSUE TITLE
Wither builder help

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [AllTheMods/ATM-6#2049]
1.7.2 version 
Wither builder does not work withers can still be spawned by hand but the builder does nothing.

**To Reproduce**
1. Make a wither builder 
2. supply it with the soul sand and skulls
3. activate the builder and see results 

Please advise if I have a lone problem or if this is indeed a bug.

**Comment by Furious1964** [comment]
Same thing is happening to me as well. This has to be looked into ASAP.

**Comment by kaedoz** [comment]
Same here

**Comment by purplesprinkles** [comment]
This is an issue with Industrial Foregoing and was fixed in: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/4b42b2a2be492af4bf46fd68dddb0e75c0d9f765.

**Comment by Furious1964** [comment]
Still not fixed. Have the latest version of IF and it still doesn't work.

**Comment by Furious1964** [comment]
New release makes it work now.

**Comment by kaedoz** [comment]
Now it is working with new release

**Comment by DevilMayCryIfrit** [comment]
Works now
