### ISSUE TITLE
Game crashes when opening any mod guidebook

### ISSUE THREAD

**Issue by Baconbiscuit53** [AllTheMods/ATM-6#2287]
**Describe the bug**
Game crashes every time I try to open the Fifty Shades of Bees book

**To Reproduce**
1. Load ATM6 v. 1.7.11
2. Craft an Akashic Tome
3. Choose any of the mod guidebooks (sans Tinkers' Construct Puny/Mighty Smelting etc.)
4. Open the book
5. Game Crashes

**Screenshots**

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
https://gist.github.com/Baconbiscuit53/657a95d3feaf2e2751bab6069060a887

**Comment by Baconbiscuit53** [comment]
updated crash log for Cyclic Guidebook
<script src="https://gist.github.com/Baconbiscuit53/efb9edf89e0e322d3e735b288c87650a.js"></script>

**Comment by ladylexxie** [comment]
Update patchouli and it should be fixed.

**Comment by Baconbiscuit53** [comment]
Patchouli is up to date. I have reinstalled it once since opening this ticket, and it did not fix the issue.

**Comment by ladylexxie** [comment]
In that case downgrade to the previous version

**Comment by Baconbiscuit53** [comment]
That also did not work unfortunately
