### ISSUE TITLE
[Question]: There are six mods that are failing to load correctly, any solutions?

### ISSUE THREAD

**Issue by jukeguy** [AllTheMods/ATM-6#3055]
### What would you like to know?

Hammerlib, create, draconic evolution, tinkers mechworks, brandons core, translocators are all not loading correctly. I have tried to look online but im not seeing anything.

**Comment by Daria40K** [comment]
I had a issue like that a few days ago. I fixed mine by running java 11 (https://github.com/AllTheMods/ATM-6/wiki/Java-Versions)

**Comment by jeremiahwinsley** [comment]
If the java version does not solve this, please post your latest.log from the launch.

**Comment by kerv17** [comment]
I've had the same exact issue, here is the log for it:
[latest.log](https://github.com/AllTheMods/ATM-6/files/8577207/latest.log)

**Comment by jeremiahwinsley** [comment]
@kerv17 in your case, you have a corrupted vanilla installation. You can try running Repair installation from the top right menu in Curseforge.

**Comment by kerv17** [comment]
Thank you very much, this fixed the issue for me!
