### ISSUE TITLE
No ender dragon in 1.3.1

### ISSUE THREAD

**Issue by NoahHagberg** [AllTheMods/ATM-6#333]
Description:
When using the server files for version 1.3.1 no ender dragon spawns, no exit portal frame exists and end gateways don't spawn.

1. Download simple server files 1.3.1
2. Start server and let world generate.
3. Use eyes of ender to locate end portal.
4. Enter the end.
5. No dragon spawns and no exit portal exists.

Expected behaviour:
The ender dragon should spawn and the exit portal should exist.

Screenshots: 
[https://imgur.com/a/CFjJ9j7](url)

Additional context:
The problem doesn't seem to exist in singleplayer.
When a world is created in singleplayer and moved to the server you can kill the dragon but no egg and no gateway will spawn. The exit portal frame won't be filled with actual portals either. The dragon also seems to drop less xp as if it was resurrected even though it is the first.

**Comment by jinkhya** [comment]
We're also experiencing that issue on our server.

**Comment by Lyror** [comment]
I have the same issue on my server

**Comment by D3s0l4ti0n** [comment]
same here ive tired a few things to fix it and no go i did find some documentation on a bug https://bugs.mojang.com/browse/MC-137467  that if your view distance is below 11 the dragon wont spawn when you enter the end but that was old but it may have something to do with dynamic view

**Comment by jinkhya** [comment]
I found a way to make it work.
I had an old 1.3.0 world with a working end.

Step by step : 

1. Stop the server.
2. From **old world/DIM1/region** copy : 
 r.0.0.mca  r.0.-1.mca r.-1.-1.mca r.-1.0.mca 
 to **your 1.3.1 world/DIM1/region** folder.
3. Start the server and break the existing end gateways on the main island (you'll need to be in creative mode to break them)
4. Stop the server.
5. In your level.dat you change DragonKilled and PreviouslyKilled values to 0 like this : 
 ![unknown](https://user-images.githubusercontent.com/10158963/99734271-cb6ef280-2ac2-11eb-9bb0-281a7ff86e9e.png)
6. Start the server and you should have an ender dragon waiting for you, you can now kill it and respawn it normally with end crystals like this issue never happened. New end gateways also spawn every time you kill the dragon. It's a bit tedious but it worked for me.

Good luck !

**Comment by ponduzn** [comment]
Same issue here, the bedrock to place the crystals on does not even spawn.

**Comment by InsideBSI** [comment]
same issue on my server running 1.3.1

**Comment by MaoamDEV** [comment]
Same Here. Server running 1.3.1
World has been generated on this version.

**Comment by InsideBSI** [comment]
I tried to lower the max render distance from dynview as I saw somewhere that it may be causing the issue and regenerated the end dimension with no success

@jinkhya could you maybe provide us the world save you used to fix this ?

**Comment by ViRb3** [comment]
This is a bug in Forge. It is currently being investigated.

**Comment by InsideBSI** [comment]
Nice to know, thanks for the information. Can you link the issue from forge ?

**Comment by InsideBSI** [comment]
Nevermind, found it https://github.com/MinecraftForge/MinecraftForge/issues/7510

**Comment by ViRb3** [comment]
Should be fixed in ATM 1.3.2c.

**Comment by RickyvdBerg** [comment]
I am still not seeing an ender dragon in 1.3.2c even after deleting the dim1 folder.

**Comment by MaoamDEV** [comment]
Just checked, and same for me.

**Comment by ViRb3** [comment]
Please check the issue linked above for a solution.
