### ISSUE TITLE
Mahou Tsukai: Cannot kill a tamed wolf to upgrade Caliburn into Morgan.

### ISSUE THREAD

**Issue by lyssieth** [AllTheMods/ATM-6#406]
**Describe the bug**
On a server (unknown if matters), we are unable to kill a tamed wolf to upgrade a Caliburn (from Mahou Tsukai) into a Morgan,

**To Reproduce**
1. Tame a wolf
2. Attempt to kill it with Caliburn

**Expected behavior**
The sword to upgrade into Morgan.

**Additional context**
While we have added mods, I tested in a plain install of the pack as well.  
Latest version as of submitting this issue is 1.3.2c, installed via Curseforge's new beta launcher.

**Comment by Pdiddy973** [comment]
fixed in 1.3.9

**Comment by realKeehan** [comment]
I still have this issue, it works for other players but not me?

**Comment by mfrischbutter** [comment]
For the ones, who are coming from ATM9: Kill the Warden with the Caliburn, and it will convert to Morgan.

I think this is a good place to share this information, as this is the second google result if you google this. 

I was able to find this information, only because a friend was in the atm discord and searched through the whole chat.
