### ISSUE TITLE
Server Hangs after receiving the stop command [KubeJS bug]

### ISSUE THREAD

**Issue by vedalken254** [AllTheMods/ATM-6#774]
**Describe the bug**
KubeJS 3.4.133+ causes the server to hang upon reaching a set point after receiving the stop command. 3.4.132 fixes the hang issue but introduces new issues in recipe parsing.

**To Reproduce**
1. Start pack version 1.3.9b fresh or an upgrade from a previous version (Doesn't matter if it's Windows or Linux)
2. Wait for server to start
3. Issue stop command
4. Server will hang after this line:
[Server thread/INFO] [FluxNetworks/]: FluxNetworkData has been unloaded

**Expected behavior**
The server to not hang after receiving the stop command.

**Additional context**
I was asked by mkaito on the discord to open this github issue.

This issue was mentioned in lesser detail in #344 and I only discovered that 3.4.132 was unaffected from this issue raised in the KubeJS repo:  KubeJS-Mods/KubeJS#51

Logfiles: https://gist.github.com/vedalken254/94956da2bac5e88e65af75401a630a9e
Screenshot of stop command hanging: https://puu.sh/H4P0I/4ce6131d45.png
Java command used to start the server for the tests: 
java -Xmx12G -Xms8G -XX:MaxMetaspaceSize=512m -Djline.terminal=jline.UnsupportedTerminal -jar ATM6Forge.jar nogui

Only changes made to the pack between the sets of log files was the version of KubeJS used as 3.4.138 is in version 1.3.9b of the pack and 3.4.132 was a manual entry as a test. Server is run headless via Multicraft with 16GB allocated to this particular MC server w/48GB RAM allocated to the Host OS. Tests were done with 12GB max RAM outside of Multicraft to be safe because not even the kill button on the panel can guaranteed save the server from the hang. My logs will show an extra line not listed in the steps to reproduce because my server.properties file was edited to have query enabled. Removing KubeJS and all its integration mods also results in proper functionality but obviously destroys the gameplay for the pack.

**Comment by Letoric** [comment]
If you self update KubeJ related mods, Rhino, and Architectury, does the issue still occur?

**Comment by Letoric** [comment]
This is fixed in the next release of the pack.

**Comment by InflamedSebi** [comment]
Issue still persists for me in version 1.4.0 of ATM6 (fresh install)

**Comment by vedalken254** [comment]
@InflamedSebi After I updated, I tested it and the issue was fixed on my server. How much RAM are you feeding the server and what arguments are you feeding to Java? I updated my Multicraft configs to use all the Java arguments specified in server-setup-config.yaml instead of just the one I'd been using in other packs which isn't in the pack's specified java args and it works fine.

**Comment by InflamedSebi** [comment]
`java -Xmx10240M -d64 -server -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Dfml.readTimeout=90 -Ddeployment.trace=true -Ddeployment.log=true -Ddeployment.trace.level=all -jar server.jar`

This is my start command. So its 10GB and the default arguments my provider recommends (hosting under ubuntu 20.4 with openjdk version "1.8.0_265")

**Comment by vedalken254** [comment]
@InflamedSebi interesting. I'm seeing a similar problem when I fresh install from Windows but not from my Linux server (Ubuntu 18.04 LTS because I'm lazy) As far as differences between your setup and the Java Args the pack ships with, I don't see anything that would jump out at me as being wrong to the point of causing it to still hang.

**Comment by vedalken254** [comment]
@InflamedSebi so on first run with a fresh install on Windows, I see it hang but after that it properly stops when told to via command line. Try it a second time and see if it hangs.

**Comment by InflamedSebi** [comment]
@vedalken254 Oh FFS. That's it. I Restarted the server a few times already, since I looked for a good seed and thus I deleted the world folder before starting every time. I just restarted it now and it works. So the issue only persists if a new world has been generated in the current session. 

Thanks :)

**Comment by ArchieBeepBoop** [comment]
@Letoric Issue persists in 1.4.0

If the world starts and immediately restarts it works fine, but the moment a player joins and generates new chunks in any area, it will hang when restarting.

**Comment by vedalken254** [comment]
@ArchieBeepBoop I have my server running through Multicraft and since the update to 1.4.0, I've not had that issue at all (even with 8 players on simultaneously though the server doesn't tend to like that many players on my hardware. Server is set up to daily restart and it works as expected. Is this a fresh install world or an upgraded world?

**Comment by OGAnthony** [comment]
Hi !

As technical manager of a Minecraft host, I confirm that this issue still presents on a fresh installation or on updated world. Over the past three days, several clients have reported the problem to me.
For information, servers running through Pterodactyl.

**Comment by ArchieBeepBoop** [comment]
> @ArchieBeepBoop I have my server running through Multicraft and since the update to 1.4.0, I've not had that issue at all (even with 8 players on simultaneously though the server doesn't tend to like that many players on my hardware. Server is set up to daily restart and it works as expected. Is this a fresh install world or an upgraded world?

Upgraded world. Also deleted the world's config files within the world save but no changes were noted.

I am however also using Linux to host this server through AMP.

**Comment by vedalken254** [comment]
That's definitely interesting as my Multicraft panel has been handling restarts perfectly fine since the update. In the case of Pterodactyl I wonder if it's still causing hangs but only in docker containers (would definitely be odd and unlikely but not impossible given my Multicraft instance is single system user setup w/ no docker configuration and it's having no problems with automatic reboots. Not sure on AMP though. What distros are you both running?

**Comment by Segaja** [comment]
I can confirm it is still hanging. here some information about my setupt:
- ubuntu 18.04
- running ATM6 1.4.0 with a world upgraded from 1.3.7 via `./startserver.sh`

I have to manually kill the process.

**Comment by ArchieBeepBoop** [comment]
> That's definitely interesting as my Multicraft panel has been handling restarts perfectly fine since the update. In the case of Pterodactyl I wonder if it's still causing hangs but only in docker containers (would definitely be odd and unlikely but not impossible given my Multicraft instance is single system user setup w/ no docker configuration and it's having no problems with automatic reboots.) Not sure on AMP though. What distros are you both running?

I'm running Ubuntu 20.04.1 LTS, ATM6 1.4.0 with a world upgraded from 1.3.7 as well. Gotta tell AMP to manually kill it otherwise it's just stuck.

**Comment by Rithenar** [comment]
I am running a server hosted on BisectHosting and I can confirm I have the same issue above. We just started a fresh new world on 1.4.0 and before anyone logged in to the server, it was restarting fine. Once the first person logged on, now the server needs to be killed every time as restarts (scheduled or not) will not work due to the server hanging on stop.

**Comment by vedalken254** [comment]
Hmmm... I'm running 18.04 and world was originally 1.3.9b before the 1.4.0 update. In 1.3.9b even a kill command from Multicraft failed to kill the process so I ran manually until the 1.4.0 update and confirmation that the issue was fixed in my case. So both fresh worlds and upgrades from at least prior to 1.3.9b are affected by this.

**Comment by legitswitch** [comment]
Was there any fix found for this? Or a mod/config causing it?
