### ISSUE TITLE
A crash caused by create

### ISSUE THREAD

**Issue by SipengXie** [AllTheMods/ATM-6#778]
```
[22:14:03] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 28ac0500-aa51-4f9b-9871-2cae0cef4b22
[22:14:03] [Render thread/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.NullPointerException: null
	at com.simibubi.create.content.contraptions.components.structureMovement.train.capability.CapabilityMinecartController.tick(CapabilityMinecartController.java:105) ~[create:mc1.16.3_v0.3c] {re:classloading}
	at com.simibubi.create.events.ClientEvents.onTick(ClientEvents.java:84) ~[create:mc1.16.3_v0.3c] {re:classloading}
```
Don't know why.

**Comment by jeremiahwinsley** [comment]
Tracked here: https://github.com/Creators-of-Create/Create/issues/684

**Comment by NULLProtogen** [comment]
I created this post:
https://github.com/AllTheMods/ATM-6/issues/793

It was closed and referred me to this post.

This post refers readers to this post:
https://github.com/Creators-of-Create/Create/issues/684

That post refers readers to this post:
https://github.com/Creators-of-Create/Create/issues/669

That post refers readers to this post:
https://github.com/henkelmax/easy-villagers/issues/32#issuecomment-756644178

That post does not have any fix and just recommends that readers open a ticket with the creators of create mod.
Is there a recommended fix? I have tried downgrading from ATM 1.3.9b to 1.3.9. I have also tried deleting my user data and temporarily moving the backup files hoping it would respawn me in a new area but it is somehow recovering my user data from an unknown location and continues to spawn me into the same spot where the game is crashing.

Do I need to downgrade further? To what version? Should I try to downgrade only the creators of create mod? To what version? Where is my user data being backed up to? Based on what I have read I think it might be possible to recover my save if I can respawn in a new area and destroy the boat that is causing me issues.

Please can anyone advise on this?

**Comment by NULLProtogen** [comment]
To anyone having this issue I have found a work around. This is what I did:

1) Shutdown Minecraft.
2) Remove create-mc1.16.3_v0.3c and kubejs-create-1604.1.0.3 from the mods folder.
3) Startup Minecraft.
4) I then got out of the boat and destroyed it. You will need to do what ever applies in your game.
5) Shutdown Minecraft.
6) Readd create-mc1.16.3_v0.3c and kubejs-create-1604.1.0.3 to the mods folder.
7) Restart Minecraft and confirm working.

Note: I have no idea if these mods created objects in the world that are now broken. I did not have any machines from this pack so I do not think I had anything break but your mileage might vary. Use this method at your own discretion and most importantly, make backups.

**Comment by jeremiahwinsley** [comment]
Unfortunately we're still waiting on Create to fix it. Recommended workaround is restore from a backup, since Create does have worldgen that would be deleted by removing it.

**Comment by Joshua-Larson** [comment]
Looks like it was fixed as of version 1.16.3_v0.3e of create. However I'm not sure how to update this specific mod (create). Should I wait for an ATM update?

**Comment by Pdiddy973** [comment]
You would just download the new file from curse forge and put it in your mods folder and remove the old version, would need to do the same for the server if you are on one...or wait till the pack updates

**Comment by joaomrsouza** [comment]
I'm on the modpack version 1.7.7 and create version 1.16.5_v0.3.2c but I'm still having this error.

I already checked the issue page for the error on the create repository and it's apparently solved, but I'm still getting my world crashing :/

Someone continues with this problem or know how to solve it?

(I think that what is crashing is the create cart assembly).
